In [1]:
import pandas as pd

In [13]:
df = pd.read_csv(r'C:\\Users\\mythi\\Downloads\\Customer shopping Details.csv')

In [3]:
df.head()

,Customer ID,Customer Name,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Colour,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code,Previous Purchase Count,Payment Method,Frequency of Purchases
0,CUST00001,Riya Kumar,56,Male,Lip Gloss,Makeup,10.58,Bengaluru,Free Size,Navy Blue,Spring,1.1,Yes,Store Pickup,No,No Promo,35,Debit Card,Rarely
1,CUST00002,Lakshmi Kumar,57,Female,Handbag,Accessories,91.68,Chennai,Free Size,Navy Blue,Autumn,2.1,Yes,Next-Day,Yes,NEWUSER,6,UPI,Monthly
2,CUST00003,Aditya Mehta,54,Male,Sweaters,Clothing,87.98,Surat,XS,Maroon,Autumn,3.3,No,Standard,No,No Promo,49,UPI,Weekly
3,CUST00004,Reyansh Pillai,70,Male,Moisturizer,Cosmetics,29.39,Madurai,Free Size,Brown,Autumn,1.8,Yes,Standard,No,No Promo,10,Cash on Delivery,Rarely
4,CUST00005,Suresh Singh,31,Male,Lip Gloss,Makeup,32.38,Mumbai,Free Size,Blue,Autumn,2.6,Yes,Store Pickup,No,No Promo,20,Debit Card,Rarely

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer ID              1000 non-null   object
 1   Customer Name            1000 non-null   object
 2   Age                      1000 non-null   int64
 3   Gender                   1000 non-null   object
 4   Item Purchased           1000 non-null   object
 5   Category                 1000 non-null   object
 6   Purchase Amount (USD)    1000 non-null   float64
 7   Location                 1000 non-null   object
 8   Size                     1000 non-null   object
 9   Colour                   1000 non-null   object
 10  Season                   1000 non-null   object
 11  Review Rating            1000 non-null   float64
 12  Subscription Status      1000 non-null   object
 13  Shipping Type            1000 non-null   object
 14  Discount Applied         1000 non-null   object
 15  Promo Code               1000 non-null   object
 16  Previous Purchase Count  1000 non-null   int64
 17  Payment Method           1000 non-null   object
 18  Frequency of Purchases   1000 non-null   object
dtypes: float64(2), int64(2), object(15)
memory usage: 148.6+ KB

In [6]:
df.describe(include='all')

,Customer ID,Customer Name,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Colour,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code,Previous Purchase Count,Payment Method,Frequency of Purchases
count,1000,1000,1000.000000,1000,1000,1000,1000.000000,1000,1000,1000,1000,1000.000000,1000,1000,1000,1000,1000.000000,1000,1000
unique,1000,556,NaN,3,34,5,NaN,20,13,17,4,NaN,2,5,2,7,NaN,6,6
top,CUST00001,Ayaan Pillai,NaN,Female,Compact Powder,Clothing,NaN,Hyderabad,Free Size,Green,Autumn,NaN,No,Free Shipping,No,No Promo,NaN,Net Banking,Rarely
freq,1,5,NaN,521,41,280,NaN,60,534,70,295,NaN,685,221,586,647,NaN,178,185
mean,NaN,NaN,42.796000,NaN,NaN,NaN,49.283560,NaN,NaN,NaN,NaN,3.022300,NaN,NaN,NaN,NaN,24.366000,NaN,NaN
std,NaN,NaN,15.693778,NaN,NaN,NaN,31.677409,NaN,NaN,NaN,NaN,1.141585,NaN,NaN,NaN,NaN,14.886627,NaN,NaN
min,NaN,NaN,16.000000,NaN,NaN,NaN,4.900000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,NaN,NaN,28.750000,NaN,NaN,NaN,24.895000,NaN,NaN,NaN,NaN,2.100000,NaN,NaN,NaN,NaN,11.000000,NaN,NaN
50%,NaN,NaN,44.000000,NaN,NaN,NaN,41.010000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,23.000000,NaN,NaN
75%,NaN,NaN,56.000000,NaN,NaN,NaN,68.725000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,37.000000,NaN,NaN
max,NaN,NaN,70.000000,NaN,NaN,NaN,149.690000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Customer Name              0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Colour                     0
Season                     0
Review Rating              0
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code                 0
Previous Purchase Count    0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [16]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [17]:
df.columns

Index(['customer_id', 'customer_name', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount', 'location', 'size', 'colour', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code', 'previous_purchase_count',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
# create a column age_group
labels = ['Young Adult','Adult',' Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4,labels = labels)

In [19]:
df[['age','age_group']].head(10)

   age     age_group
0   56   Middle-aged
1   57        Senior
2   54   Middle-aged
3   70        Senior
4   31         Adult
5   47   Middle-aged
6   25   Young Adult
7   64        Senior
8   25   Young Adult
9   62        Senior

In [20]:
df[['discount_applied','promo_code']].head(10)

  discount_applied promo_code
0               No   No Promo
1              Yes    NEWUSER
2               No   No Promo
3               No   No Promo
4               No   No Promo
5               No   No Promo
6               No   No Promo
7               No   No Promo
8              Yes     SAVE20
9               No   No Promo

In [22]:
(df['discount_applied'] == df['promo_code']).all()

np.False_

In [24]:
df = df.drop('promo_code', axis=1)

In [25]:
df.columns

Index(['customer_id', 'customer_name', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount', 'location', 'size', 'colour', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchase_count', 'payment_method',
       'frequency_of_purchases', 'age_group'],
      dtype='object')

In [26]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\mythi\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\mythi\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mythi\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [27]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:@localhost:3306/Customer_shopping_db')

In [29]:
# Database create பண்ணுங்க
conn = pymysql.connect(host='localhost', user='root', password='Mythili2006')
cursor = conn.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS customer_shopping_db")
conn.close()
print("Database created!")

Database created!